---
- name: create a ngnix server on vm 
  hosts: vm_server
  become: yes  
  tasks:
  - name: install nginx server on vm
    apt:
      name: nginx
      state: present
  - name: start nginx server on vm 
    service:
      name : nginx
      state: started
        


