---
- name: create a ngnix server on vm 
  hosts: vm_server
  become: yes  
  tasks:
  - name: uninstall nginx server on vm
    apt:
      name: nginx
      state: absent 
  - name: stop nginx server on vm 
    service:
      name : nginx
      state: stopped


